### ISSUE TITLE
How can use Agones without cert?

### ISSUE THREAD

**Issue by laivu266** [Octops/agones-discover-openmatch#2]
Hi there,

Because we deploy agones and agones-openmatch in one cluster, so how can use mode=agones without add cert in args?

Thanks.

**Comment by danieloliveira079** [comment]
Hello @laivu266,

Unfortunately this is not possible due to the way Agones Allocation Service works.

Have a look at https://github.com/Octops/agones-discover-openmatch/blob/main/docs/agones-allocator.md and the full documentation from the Agones website https://agones.dev/site/docs/advanced/allocator-service/.

The allocation service uses mTLS for authentication and that is a requirement for clients.

What kind of problems are you facing right now? Did you manage to mount the right certificates files inside the Pod and passing the path in the args list?

**Comment by danieloliveira079** [comment]
Feel free to reopen this issue if you still have questions.
